# variables
@id = 00000000-0000-0000-0000-000000000000

# request method, url, & headers
PUT http://localhost:8080/admin/products/{{id}}
Content-Type: application/json
Authorization: secret

# body
{
    "name": "Shiny Thing",
    "price": 10000
}



